[[pages]]
path = 'app.py'
name = 'Home'

[[pages]]
path = 'pages/projects_page.py'
name = 'Projects'

[[pages]]
path = 'pages/import_data_page.py'
name = 'Data Import'

[[pages]]
path = 'pages/views_page.py'
name = 'Views'

[[pages]]
path = 'pages/advanced_views_page.py'
name = 'Advanced Views'

[[pages]]
path = 'pages/dq_metrics_page.py'
name = 'DQ Metrics'
